name: CI

on:
  push:

jobs:
  lint_and_test:
    runs-on: [self-hosted, small]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install yarn
        run: |
          npm install --global yarn

      - name: Dependency cache
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-banned-assets-v1-${{ hashFiles('yarn.lock') }}

      - name: Install packages dependencies
        run: |
          yarn install --prefer-offline --frozen-lockfile

      - name: Check lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn test